name: CodeWork-Marketing-Production-AWS

on:
  push:
    branches:
      - newchange
  workflow_dispatch:

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # Step 3: Cache Node modules
      - name: Cache Node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # Step 4: Install dependencies
      - name: Install Dependencies
        run: npm ci --legacy-peer-deps

      # Step 5: Disable Next.js telemetry
      - name: Disable Next.js telemetry
        run: npx next telemetry disable

      # Step 6: Cache Next.js build
      - name: Cache Next.js build
        uses: actions/cache@v3
        with:
          path: .next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-

      # Step 7: Build Application
      - name: Build Application
        run: npm run build

      # Step 8: Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      # Step 9: Deploy to S3
      - name: Deploy to S3
        run: |
          aws s3 sync ./out s3://code-site-9-1-2026 --delete
