name: Deploy to S3

on:
  push:
    branches:
      - main   # Run when pushing to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AKIA2GL6C23NKBLHTMOG }}
          aws-secret-access-key: ${{ secrets.oifqiKHqtbsXw3tQYTHnqDscWLAG6PNVjRF/GD1j}}
          aws-region: us-east-1   # change your region

      - name: Sync files to S3
        run: |
          aws s3 sync ./your-folder s3://code-site-9-1-2026 --delete
